version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

exclude_patterns = [
  "migrations/**",
  "**/examples/**"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["requirements.txt", "requirements-stdborg.txt"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  
